USE FashionStoreManager
GO


SELECT * FROM CUSTOMER;
SELECT * FROM CART;	
SELECT * FROM EMPLOYEE;	
SELECT * FROM BRANCH;	
SELECT * FROM ACCOUNT;	
SELECT * FROM CUSTOMER_PHONE;		
SELECT * FROM CUSTOMER_EMAIL;	
SELECT * FROM MATERIAL;	
SELECT * FROM MATERIAL_CHARACTERISTIC;	
SELECT * FROM CATEGORY;	
SELECT * FROM EMPLOYEE_PHONE;	
SELECT * FROM EMPLOYEE_EMAIL;	
SELECT * FROM SHOWROOM_BRANCH;
SELECT * FROM ONLINE_BRANCH;
SELECT * FROM FURNITURE;	
SELECT * FROM _ORDER;		
SELECT * FROM ORDER_BRANCH;  
SELECT * FROM PROMOTION;	
SELECT * FROM SHIPPING;	
SELECT * FROM ORDER_ONLINE;	
SELECT * FROM SUPPLIER;	
SELECT * FROM SUPPLIER_PHONE;	
SELECT * FROM PRODUCT;
SELECT * FROM CART_PRODUCT;
SELECT * FROM CLOTHES;	
SELECT * FROM SHOE;	
SELECT * FROM PRODUCT_USE_MATERIAL;	
SELECT * FROM PRODUCT_OF_ORDER;
SELECT * FROM _ORDER;
SELECT * FROM PAYMENT

-- Kiểm tra các kết quả tính toán 
SELECT o.total_money,p.promotion_id, pr.min_money as Min_promotion, pr.max_money as Max_promotion, pr.promotion_percent as PhanTram,dbo.TinhKM(p.order_id,p.promotion_id) as KM_money ,p.total_money FROM _ORDER o, PAYMENT p, PROMOTION pr WHERE o.order_id = p.order_id and pr.promotion_id = p.promotion_id
GO